version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

  server:
    build: ./server
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern-crud-new
    ports:
      - "5000:5000"

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
